services:
  - type: web
    name: cryptodog-clock
    env: python
    buildCommand: ""
    startCommand: python app.py
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production

